#!/usr/bin/env bash
# postprocess-raw.sh — run after `cargo progenitor` regenerates harmont-cloud-raw.
#
# Progenitor overwrites Cargo.toml (losing workspace-inheritance) and drops the
# do-not-edit banner from src/lib.rs.  This script restores both so that
# `make codegen-sdk-rs` leaves git status clean.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDK_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
RAW_DIR="${SDK_DIR}/harmont-cloud-raw"
TMPL="${SDK_DIR}/harmont-cloud-raw.Cargo.toml.tmpl"
LIBRS="${RAW_DIR}/src/lib.rs"
BANNER='//! GENERATED by `make codegen-sdk-rs` (progenitor). Do not edit by hand.'

# ── 1. Restore pinned Cargo.toml ────────────────────────────────────────────
cp "${TMPL}" "${RAW_DIR}/Cargo.toml"
echo "postprocess-raw: restored harmont-cloud-raw/Cargo.toml from template"

# ── 2. Ensure banner is the first line of src/lib.rs ────────────────────────
first_line="$(head -n 1 "${LIBRS}")"

if [[ "${first_line}" == "${BANNER}" ]]; then
    echo "postprocess-raw: banner already present in src/lib.rs"
else
    # If progenitor wrote a different //! doc comment on line 1, leave it in
    # place but prepend our banner above it.  This keeps the file idempotent
    # regardless of what progenitor emits.
    tmp="$(mktemp)"
    { printf '%s\n' "${BANNER}"; cat "${LIBRS}"; } > "${tmp}"
    mv "${tmp}" "${LIBRS}"
    echo "postprocess-raw: prepended banner to src/lib.rs"
fi
