import Config

# Configure your database
config :harmont_core, Harmont.Repo,
  username: System.get_env("PGUSER", "harmont"),
  password: System.get_env("PGPASSWORD", "harmont"),
  hostname: System.get_env("PGHOST", "localhost"),
  database: "harmont_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :harmont_web, HarmontWeb.Endpoint,
  # Loopback by default. scripts/dev-up.sh sets DEV_BIND_ALL=1 so the endpoint
  # binds all interfaces and is reachable over Tailscale (the user's laptop hits
  # this dev box remotely — see scripts/dev-up.sh).
  http: [
    ip: if(System.get_env("DEV_BIND_ALL") in ~w(1 true), do: {0, 0, 0, 0}, else: {127, 0, 0, 1}),
    port: 4000
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "VKkm3xBYdLZuSglhtwrVoOJcxxf41UdE/uVcMl2aZ949A918fZfBCbogussJP3zK",
  watchers: []

# CORS: allow the local SPA dev origin to call the API.
config :harmont_web, HarmontWeb.Cors, allowed_origins: ["http://localhost:8765"]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :harmont_web, dev_routes: true

config :harmont_vm, :backend, HarmontVm.Backend.Local

# The Local VM backend has no in-VM agent ("no real VM, no agent"), so jobs must
# run in local mode — the Session executes the command directly via run_local.
# Without this, jobs default to agent mode (use_agent? defaults to true) and wait
# for an agent that never connects, failing with `agent_connect_deadline` after
# ~120s. test.exs pairs these two settings the same way.
config :harmont_engine, :use_agent, false

# Oban Pro encrypted-args key (Task 8): a FIXED 32-byte, Base64-encoded dev key.
# Dev only — prod fetches its key from HARMONT_OBAN_ENCRYPTION_KEY (runtime.exs).
config :harmont_core, :oban_encryption_key, "fc9fw9Im89JAMN21aXs2ZQ1/8u+mz9LFm56oYOXS/eg="

# Fixed dev/test Cloak key — 32 bytes, Base64. Prod uses HARMONT_CLOAK_KEY (runtime.exs).
config :harmont_core, Harmont.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1",
       key: Base.decode64!("fc9fw9Im89JAMN21aXs2ZQ1/8u+mz9LFm56oYOXS/eg="),
       iv_length: 12}
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Mailer: render to the Swoosh local mailbox (browsable at /dev/mailbox) instead
# of sending. The SPA runs on :8765 in dev, so email links point there.
config :harmont_api, HarmontApi.Mailer, adapter: Swoosh.Adapters.Local
config :harmont_api, :app_base_url, "http://localhost:8765"

# WebAuthn: passkeys are scoped to localhost in dev; origin is the SPA's dev URL.
config :harmont_api, :webauthn, rp_id: "localhost", origin: "http://localhost:8765"

# OAuth: real Google/GitHub credentials can be supplied via env (same var names
# as prod) so social sign-in works locally; otherwise the config.exs
# placeholders apply and the real token exchange is simply never exercised.
# scripts/dev-up.sh exports these from .hm-dev-env.
config :harmont_api, :oauth,
  google: [
    client_id: System.get_env("GOOGLE_OAUTH_CLIENT_ID", "dev-google-client-id"),
    client_secret: System.get_env("GOOGLE_OAUTH_CLIENT_SECRET", "dev-google-client-secret")
  ],
  github: [
    client_id: System.get_env("GITHUB_OAUTH_CLIENT_ID", "dev-github-client-id"),
    client_secret: System.get_env("GITHUB_OAUTH_CLIENT_SECRET", "dev-github-client-secret")
  ]

# Stripe: dev points the post-checkout redirects at the local SPA. The API key
# and webhook secret fall back to placeholders (config.exs) unless real env
# vars are set; the real Stripe boundary is never exercised without real creds.
config :harmont_api, :stripe,
  webhook_secret: System.get_env("STRIPE_WEBHOOK_SECRET", "whsec_placeholder"),
  checkout_success_url: "http://localhost:8765/billing/success",
  checkout_cancel_url: "http://localhost:8765/billing/cancel"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
