%{
  configs: [
    %{
      name: "default",
      files: %{
        included: [
          "apps/*/lib/",
          "apps/*/test/",
          "apps/*/config/"
        ],
        excluded: [
          # Generated protobuf stubs — not hand-written; regenerated by `mix proto.gen`.
          "apps/harmont_engine/lib/harmont/proto/",
          ~r"/_build/",
          ~r"/deps/"
        ]
      },
      strict: true,
      checks: %{
        extra: [],
        disabled: [
          # The `freestyle/lib/freestyle/types/` files hold public typed-struct
          # submodules (one per API type). Documenting dozens of bare data-container
          # modules with @moduledoc false would be noisier than useful; the parent
          # module's @moduledoc covers the whole types file.
          {Credo.Check.Readability.ModuleDoc,
           files: %{included: ["apps/freestyle/lib/freestyle/types/"]}}
        ]
      }
    }
  ]
}
