import { defineConfig } from "@hey-api/openapi-ts";

// Input is the committed spec artifact (regenerated by `make codegen`).
// Output is gitignored: the SDK is a build artifact, never committed.
export default defineConfig({
  input: "../../elixir/apps/harmont_api/priv/static/openapi.json",
  output: { path: "src/generated", clean: true, postProcess: ["prettier"] },
  plugins: ["@hey-api/client-fetch", "@hey-api/sdk", "@hey-api/typescript"],
});
