#!/usr/bin/env bash
# Seed .hm-dev-env for Bombadil unauthenticated / bad-token test runs.
#
#   scripts/dev-seed-anon.sh         → empty token (SPA boots anonymous)
#   scripts/dev-seed-anon.sh --bad   → syntactically-valid garbage token
#                                       (API rejects → app must bounce to /login)
#
# Preserves HARMONT_API_URL / HARMONT_ORG / OAuth client ids from an existing
# .hm-dev-env if present; only the token is overridden. After running this,
# start the stack with scripts/dev-up.sh in your own terminal.
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".hm-dev-env"

MODE="anon"
if [ "${1:-}" = "--bad" ]; then
  MODE="bad"
fi

# Carry over non-token settings if a real env file exists.
API_URL="http://localhost:3000"
ORG="default"
GOOGLE_CLIENT_ID=""
GH_OAUTH_CLIENT_ID=""
GH_APP_SLUG="harmont-app"
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  API_URL="${HARMONT_API_URL:-$API_URL}"
  ORG="${HARMONT_ORG:-$ORG}"
  GOOGLE_CLIENT_ID="${HARMONT_GOOGLE_CLIENT_ID:-}"
  GH_OAUTH_CLIENT_ID="${HARMONT_GITHUB_OAUTH_CLIENT_ID:-}"
  GH_APP_SLUG="${HARMONT_GITHUB_APP_SLUG:-harmont-app}"
fi

if [ "$MODE" = "bad" ]; then
  TOKEN="hmt_deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  echo "→ Seeding BAD token (API will reject; app should redirect to /login)"
else
  TOKEN=""
  echo "→ Seeding EMPTY token (anonymous mode)"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev-seed-anon.sh (mode=$MODE) — for Bombadil test runs. Do not commit.
HARMONT_API_URL=$API_URL
HARMONT_TOKEN=$TOKEN
HARMONT_ORG=$ORG
HARMONT_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
HARMONT_GITHUB_OAUTH_CLIENT_ID=$GH_OAUTH_CLIENT_ID
HARMONT_GITHUB_APP_SLUG=$GH_APP_SLUG
EOF
chmod 600 "$ENV_FILE"

echo "→ Wrote $ENV_FILE (mode=$MODE). Now run scripts/dev-up.sh in your own terminal."
