#!/bin/bash
# Seed the local Elixir dev database with a usable fixture: a dev user, a
# `default` org, a fixed dev API token, a sample pipeline, and a few
# builds/jobs/log lines. Idempotent — safe to run repeatedly. Writes
# credentials to .hm-dev-env.
#
# The seed logic lives in Elixir (apps/harmont_core/priv/repo/seeds.exs) so it
# can't drift from the Ecto schema; this script is a thin wrapper that waits for
# the backend, runs the seed, verifies the token, and writes the env file.
#
# Auth note: Harmont has no email+password endpoint (sign-in is passkey / OAuth
# / CLI, none of which is scriptable headlessly). Auth is token-convergent —
# every bearer is the SHA-256 of a row in `api_tokens` — so the seed mints the
# dev token directly via the real token path.
#
# Requires: the Elixir backend running on localhost:4000 and PostgreSQL up
# (both started by scripts/dev-up.sh).
set -euo pipefail

API_URL="${HARMONT_API_URL:-http://localhost:4000}"
ORG_SLUG="default"
PIPELINE_SLUG="demo"

# Stable, local-only dev bearer. This is NOT a secret — it only grants access to
# a localhost dev database. Must match `dev_token` in seeds.exs.
DEV_TOKEN="hmt_localdev_devseed"

cd "$(dirname "$0")/.."

# --- Wait for the backend (also confirms the DB is migrated and reachable) ---
echo "→ Waiting for the Elixir backend at $API_URL..."
for i in $(seq 1 30); do
  if curl -fs "$API_URL/api/v0/ping" > /dev/null 2>&1; then
    echo "  ✓ backend is up"
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "  ✗ backend did not come up in 30s." >&2
    echo "    Is the Elixir backend (scripts/dev-up.sh / mix phx.server) running?" >&2
    exit 1
  fi
  sleep 1
done

# --- Run the Elixir seed (idempotent) ----------------------------------------
echo "→ Seeding user, org, token, pipeline, builds, jobs, logs..."
(cd elixir && mix run apps/harmont_core/priv/repo/seeds.exs)

# --- Sanity-check the token authenticates ------------------------------------
if ! curl -fs -H "Authorization: Bearer $DEV_TOKEN" "$API_URL/api/v0/user" > /dev/null 2>&1; then
  echo "  ✗ Minted token failed to authenticate against $API_URL/api/v0/user." >&2
  echo "    Is the backend pointed at the harmont_dev database?" >&2
  exit 1
fi
echo "  ✓ token authenticates"

# --- Write env file ----------------------------------------------------------
cat > .hm-dev-env <<EOF
# Generated by scripts/dev-seed.sh. Do not commit.
HARMONT_API_URL=$API_URL
HARMONT_TOKEN=$DEV_TOKEN
HARMONT_ORG=$ORG_SLUG
EOF
chmod 600 .hm-dev-env

cat <<EOF

✓ Dev environment ready
  Org:      $ORG_SLUG
  Pipeline: $PIPELINE_SLUG
  Token:    written to .hm-dev-env (Authorization: Bearer $DEV_TOKEN)
EOF
