import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { sdkFunctions, renderSignature, type SdkFunction } from '../lib/sdk-api';

const OUT_ROOT = 'content/docs/sdk/reference';

// Human titles for tags whose default capitalization is wrong. Any other tag
// falls back to capitalize() in titleFor(), so only list the exceptions.
const TAG_TITLES: Record<string, string> = {
  github: 'GitHub',
};

function titleFor(tag: string): string {
  return TAG_TITLES[tag] ?? tag.charAt(0).toUpperCase() + tag.slice(1);
}

// Escape MDX-hostile chars in prose taken from spec descriptions.
function esc(s: string): string {
  return s.replace(/([{}<])/g, '\\$1');
}

function tcode(s: string): string {
  return '`' + s.replace(/\|/g, '\\|') + '`';
}

function paramTable(fn: SdkFunction): string[] {
  const rows = [
    ...fn.pathParams.map((p) => `| ${tcode(p.name)} | path | ${tcode(p.type)} | ${p.doc ? esc(p.doc) : '—'} |`),
    ...fn.queryParams.map((p) => `| ${tcode(p.name)} | query | ${tcode(p.type)} | ${p.doc ? esc(p.doc) : '—'} |`),
  ];
  if (rows.length === 0) return [];
  return ['', '| Parameter | In | Type | Description |', '| --- | --- | --- | --- |', ...rows];
}

function functionSection(fn: SdkFunction): string[] {
  const out = [`### \`${fn.name}\``, '', '`' + `${fn.method} ${fn.path}` + '`'];
  if (fn.summary.trim()) out.push('', esc(fn.summary.trim()));
  const body = fn.description.trim();
  if (body && body !== fn.summary.trim()) out.push('', esc(body));
  out.push('', '```ts', `import { ${fn.name} } from "@harmont/cloud";`, '```');
  out.push('', '```ts', renderSignature(fn), '```');
  out.push(...paramTable(fn));
  if (fn.requestBody) {
    out.push('', `**Body** ${tcode(fn.requestBody.type)}${fn.requestBody.required ? ' (required)' : ' (optional)'}`);
  }
  out.push('', `**Returns** ${tcode(fn.responseType)}`);
  out.push('', `See [\`${fn.method} ${fn.path}\`](/api/reference/${fn.tag}) for the full request and response schema.`);
  return out;
}

function pageBody(tag: string, fns: SdkFunction[]): string {
  const title = titleFor(tag);
  const header = [
    '---',
    `title: ${title}`,
    `description: Generated @harmont/cloud reference for the ${title} endpoints.`,
    '---',
    '',
    '{/* Generated by docs-site/scripts/generate-sdk-docs.ts — do not edit. */}',
    '',
    '',
  ].join('\n');
  const sorted = [...fns].sort((a, b) => a.name.localeCompare(b.name));
  return header + sorted.map((f) => functionSection(f).join('\n')).join('\n\n') + '\n';
}

function main(): void {
  rmSync(OUT_ROOT, { recursive: true, force: true });
  mkdirSync(OUT_ROOT, { recursive: true });

  const byTag = new Map<string, SdkFunction[]>();
  for (const fn of sdkFunctions) {
    const list = byTag.get(fn.tag) ?? [];
    list.push(fn);
    byTag.set(fn.tag, list);
  }

  const tags = [...byTag.keys()].sort((a, b) => titleFor(a).localeCompare(titleFor(b)));
  for (const tag of tags) {
    writeFileSync(join(OUT_ROOT, `${tag}.mdx`), pageBody(tag, byTag.get(tag)!), 'utf8');
  }

  const indexLinks = tags.map((t) => `- [${titleFor(t)}](/sdk/reference/${t})`).join('\n');
  writeFileSync(
    join(OUT_ROOT, 'index.mdx'),
    [
      '---',
      'title: Reference',
      'description: Every public @harmont/cloud function, generated from the OpenAPI spec.',
      '---',
      '',
      '{/* Generated by docs-site/scripts/generate-sdk-docs.ts — do not edit. */}',
      '',
      'One function per public endpoint, grouped by tag. Each shows the import, the',
      'call signature, parameters, and a link to the full schema in the',
      '[API reference](/api/reference).',
      '',
      indexLinks,
      '',
    ].join('\n'),
    'utf8',
  );

  writeFileSync(
    join(OUT_ROOT, 'meta.json'),
    JSON.stringify({ title: 'Reference', pages: ['index', ...tags] }, null, 2) + '\n',
    'utf8',
  );

  console.log(`generate-sdk-docs: wrote ${tags.length} tag pages + index from ${sdkFunctions.length} functions`);
}

main();
