import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  dslSymbols,
  renderSignature,
  type DslMethod,
  type DslSignatureData,
  type DslSymbol,
} from '../lib/dsl-api';

const OUT_ROOT = 'content/docs/pipeline-sdk/reference';

const PAGE_TITLES: Record<string, string> = {
  chains: 'Chains & steps',
  pipeline: 'Pipeline',
  cache: 'Cache policies',
  triggers: 'Triggers',
  'toolchains/rust': 'Rust',
  'toolchains/python': 'Python',
  'toolchains/go': 'Go',
  'toolchains/js': 'JavaScript / TypeScript',
  'toolchains/zig': 'Zig',
  'toolchains/cmake': 'CMake',
  'toolchains/elixir': 'Elixir',
  'toolchains/base': 'Base images',
};

// Escape MDX-hostile chars in prose taken from docstrings, and normalize the
// reader-facing product name: the upstream SDK docstrings still say "DSL", but
// the docs call it the pipeline SDK.
function esc(s: string): string {
  return s.replace(/\bDSL\b/g, 'pipeline SDK').replace(/([{}<])/g, '\\$1');
}

// A `code` cell for a markdown table: literal pipes (e.g. in `str | None`)
// must be escaped or they split the row into extra columns. GFM renders the
// escaped pipe as a literal `|` inside the code span.
function tcode(s: string | null): string {
  return s ? '`' + s.replace(/\|/g, '\\|') + '`' : '—';
}

function tprose(s: string): string {
  return s ? esc(s).replace(/\|/g, '\\|') : '—';
}

// The docstring `description` is the full text and begins with `summary`;
// return only the part after the summary, so prose isn't printed twice.
function bodyAfterSummary(summary: string, description: string): string {
  const s = summary.trim();
  const d = description.trim();
  if (!d || d === s) return '';
  return d.startsWith(s) ? d.slice(s.length).trim() : d;
}

function fence(body: string): string {
  return ['```python', body, '```'].join('\n');
}

function examples(ex: string[]): string[] {
  return ex.length ? ['', '**Examples**', '', fence(ex.join('\n'))] : [];
}

function paramTable(sig: DslSignatureData): string[] {
  if (sig.params.length === 0) return [];
  const rows = sig.params.map((p) => {
    const def = p.default === null ? '_required_' : tcode(p.default);
    return `| ${tcode(p.name)} | ${tcode(p.annotation)} | ${def} | ${tprose(p.doc)} |`;
  });
  return [
    '',
    '| Parameter | Type | Default | Description |',
    '| --- | --- | --- | --- |',
    ...rows,
  ];
}

function returnsLine(sig: DslSignatureData): string[] {
  const { annotation, doc } = sig.returns;
  if (!annotation && !doc) return [];
  const t = annotation ? `\`${annotation}\`` : '';
  return ['', `**Returns** ${t}${doc ? ` — ${esc(doc)}` : ''}`];
}

function method(symName: string, m: DslMethod): string[] {
  const out = [`### \`${symName}.${m.name}()\``, '', fence(renderSignature(m.name, m.signature))];
  if (m.summary.trim()) out.push('', esc(m.summary.trim()));
  const body = bodyAfterSummary(m.summary, m.description);
  if (body) out.push('', esc(body));
  out.push(...paramTable(m.signature), ...returnsLine(m.signature), ...examples(m.examples));
  return out;
}

function symbolSection(sym: DslSymbol): string[] {
  const out: string[] = [`## \`${sym.name}\``];
  if (sym.summary.trim()) out.push('', esc(sym.summary.trim()));
  const body = bodyAfterSummary(sym.summary, sym.description);
  if (body) out.push('', esc(body));
  if (sym.signature) {
    out.push('', fence(renderSignature(sym.name, sym.signature)));
    out.push(...paramTable(sym.signature), ...returnsLine(sym.signature));
  }
  if (sym.kind === 'dataclass' && sym.fields.length > 0) {
    out.push('', '### Fields', '', '| Field | Type | Default |', '| --- | --- | --- |');
    for (const f of sym.fields) {
      const def = f.default === null ? '_required_' : tcode(f.default);
      out.push(`| ${tcode(f.name)} | ${tcode(f.annotation)} | ${def} |`);
    }
  }
  out.push(...examples(sym.examples));
  for (const m of sym.methods) out.push('', ...method(sym.name, m));
  return out;
}

function titleFor(page: string): string {
  if (PAGE_TITLES[page]) return PAGE_TITLES[page];
  const tail = page.split('/').pop() ?? page;
  return tail.charAt(0).toUpperCase() + tail.slice(1);
}

function pageBody(page: string, syms: DslSymbol[]): string {
  const title = titleFor(page);
  const header = [
    '---',
    `title: ${title}`,
    `description: Generated reference for the harmont ${title} API.`,
    '---',
    '',
    '{/* Generated by docs-site/scripts/generate-dsl-docs.ts — do not edit. */}',
    '',
    '',
  ].join('\n');
  const sorted = [...syms].sort((a, b) => a.name.localeCompare(b.name));
  return header + sorted.map((s) => symbolSection(s).join('\n')).join('\n\n') + '\n';
}

function main(): void {
  rmSync(OUT_ROOT, { recursive: true, force: true });
  mkdirSync(OUT_ROOT, { recursive: true });

  const byPage = new Map<string, DslSymbol[]>();
  for (const sym of dslSymbols) {
    const list = byPage.get(sym.page) ?? [];
    list.push(sym);
    byPage.set(sym.page, list);
  }

  const pages = [...byPage.keys()];
  for (const page of pages) {
    const file = join(OUT_ROOT, `${page}.mdx`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, pageBody(page, byPage.get(page)!), 'utf8');
  }

  const topPages = pages
    .filter((p) => !p.includes('/'))
    .sort((a, b) => titleFor(a).localeCompare(titleFor(b)));
  const hasToolchains = pages.some((p) => p.startsWith('toolchains/'));
  const indexLinks = [
    ...topPages.map((p) => `- [${titleFor(p)}](/pipeline-sdk/reference/${p})`),
    ...(hasToolchains ? ['- [Toolchains](/pipeline-sdk/reference/toolchains)'] : []),
  ].join('\n');
  writeFileSync(
    join(OUT_ROOT, 'index.mdx'),
    [
      '---',
      'title: Reference',
      'description: Every public function, class, and toolchain in the harmont pipeline SDK.',
      '---',
      '',
      '{/* Generated by docs-site/scripts/generate-dsl-docs.ts — do not edit. */}',
      '',
      'The complete public surface of the `harmont` package, generated from the source.',
      '',
      indexLinks,
      '',
    ].join('\n'),
    'utf8',
  );

  writeFileSync(
    join(OUT_ROOT, 'meta.json'),
    JSON.stringify(
      { title: 'Reference', pages: ['index', ...topPages, ...(hasToolchains ? ['toolchains'] : [])] },
      null,
      2,
    ) + '\n',
    'utf8',
  );

  const toolchainPages = pages
    .filter((p) => p.startsWith('toolchains/'))
    .map((p) => p.split('/')[1])
    .sort((a, b) => titleFor(`toolchains/${a}`).localeCompare(titleFor(`toolchains/${b}`)));
  if (toolchainPages.length > 0) {
    writeFileSync(
      join(OUT_ROOT, 'toolchains', 'meta.json'),
      JSON.stringify({ title: 'Toolchains', pages: toolchainPages }, null, 2) + '\n',
      'utf8',
    );
  }

  console.log(
    `generate-dsl-docs: wrote ${pages.length} pages + index from ${dslSymbols.length} symbols`,
  );
}

main();
